// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFeed = `-- name: AddFeed :one
INSERT INTO feeds (id, created_at, updated_at, name, url, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, name, url, user_id
`

type AddFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) AddFeed(ctx context.Context, arg AddFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, addFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const getFeedIDAndNameFromURL = `-- name: GetFeedIDAndNameFromURL :one
SELECT id, name
FROM feeds
WHERE url = $1
`

type GetFeedIDAndNameFromURLRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetFeedIDAndNameFromURL(ctx context.Context, url string) (GetFeedIDAndNameFromURLRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedIDAndNameFromURL, url)
	var i GetFeedIDAndNameFromURLRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many
SELECT name, url, user_id
FROM feeds
`

type GetFeedsRow struct {
	Name   string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) GetFeeds(ctx context.Context) ([]GetFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
